/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klinikkebidanan;

/**
 *
 * @author FAJAR
 */
public class Form_informasi extends javax.swing.JFrame {

    /**
     * Creates new form Informasi
     */
    public Form_informasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nomor_pemeriksaan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Pasien = new javax.swing.JButton();
        Obat = new javax.swing.JButton();
        Bidan = new javax.swing.JButton();
        Kode_tindakan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Nomor_pendaftaran = new javax.swing.JButton();
        Nomor_pemeriksaan1 = new javax.swing.JButton();
        Nomor_transaksi = new javax.swing.JButton();

        Nomor_pemeriksaan.setBackground(new java.awt.Color(255, 255, 255));
        Nomor_pemeriksaan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Nomor_pemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/stethoscope(1).png"))); // NOI18N
        Nomor_pemeriksaan.setText("Nomor Pemeriksaan");
        Nomor_pemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nomor_pemeriksaanActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        Pasien.setBackground(new java.awt.Color(255, 255, 255));
        Pasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/expecting.png"))); // NOI18N
        Pasien.setText("Pasien");
        Pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasienActionPerformed(evt);
            }
        });

        Obat.setBackground(new java.awt.Color(255, 255, 255));
        Obat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/medicine.png"))); // NOI18N
        Obat.setText("Obat");
        Obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObatActionPerformed(evt);
            }
        });

        Bidan.setBackground(new java.awt.Color(255, 255, 255));
        Bidan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/doctor.png"))); // NOI18N
        Bidan.setText("Bidan");
        Bidan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BidanActionPerformed(evt);
            }
        });

        Kode_tindakan.setBackground(new java.awt.Color(255, 255, 255));
        Kode_tindakan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/medical-kit.png"))); // NOI18N
        Kode_tindakan.setText("Kode Tindakan");
        Kode_tindakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kode_tindakanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        jLabel1.setText("Informasi");

        Nomor_pendaftaran.setBackground(new java.awt.Color(255, 255, 255));
        Nomor_pendaftaran.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Nomor_pendaftaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/note(1).png"))); // NOI18N
        Nomor_pendaftaran.setText("No.Pendaftaran");
        Nomor_pendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nomor_pendaftaranActionPerformed(evt);
            }
        });

        Nomor_pemeriksaan1.setBackground(new java.awt.Color(255, 255, 255));
        Nomor_pemeriksaan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/stethoscope(1).png"))); // NOI18N
        Nomor_pemeriksaan1.setText("No.Pemeriksaan");
        Nomor_pemeriksaan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nomor_pemeriksaan1ActionPerformed(evt);
            }
        });

        Nomor_transaksi.setBackground(new java.awt.Color(255, 255, 255));
        Nomor_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/get-money.png"))); // NOI18N
        Nomor_transaksi.setText("No.Transaksi");
        Nomor_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nomor_transaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Nomor_pendaftaran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(Nomor_pemeriksaan1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Obat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Pasien, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Kode_tindakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bidan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(Nomor_transaksi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pasien, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bidan, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Obat, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kode_tindakan, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nomor_pendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nomor_pemeriksaan1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Nomor_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(391, 516));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasienActionPerformed
     new Form_pasien().setVisible(true);
    }//GEN-LAST:event_PasienActionPerformed

    private void BidanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BidanActionPerformed
     new Form_bidan().setVisible(true);
    }//GEN-LAST:event_BidanActionPerformed

    private void ObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObatActionPerformed
   new Form_obat().setVisible(true);
    }//GEN-LAST:event_ObatActionPerformed

    private void Kode_tindakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kode_tindakanActionPerformed
    new Form_kode_tindakan().setVisible(true);
    }//GEN-LAST:event_Kode_tindakanActionPerformed

    private void Nomor_pendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nomor_pendaftaranActionPerformed
        new Form_nomor_pendaftaran().setVisible(true);
    }//GEN-LAST:event_Nomor_pendaftaranActionPerformed

    private void Nomor_pemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nomor_pemeriksaanActionPerformed
        new Form_nomor_pemeriksaan().setVisible(true);
    }//GEN-LAST:event_Nomor_pemeriksaanActionPerformed

    private void Nomor_pemeriksaan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nomor_pemeriksaan1ActionPerformed
        new Form_nomor_pemeriksaan().setVisible(true);
    }//GEN-LAST:event_Nomor_pemeriksaan1ActionPerformed

    private void Nomor_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nomor_transaksiActionPerformed
        new Form_nomor_transaksi().setVisible(true);
    }//GEN-LAST:event_Nomor_transaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_informasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_informasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_informasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_informasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_informasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bidan;
    private javax.swing.JButton Kode_tindakan;
    private javax.swing.JButton Nomor_pemeriksaan;
    private javax.swing.JButton Nomor_pemeriksaan1;
    private javax.swing.JButton Nomor_pendaftaran;
    private javax.swing.JButton Nomor_transaksi;
    private javax.swing.JButton Obat;
    private javax.swing.JButton Pasien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
 
    void hakAksesAdministrasi() {
        Pasien.setEnabled(true);
        Bidan.setEnabled(true);
        Kode_tindakan.setEnabled(true);
        Obat.setEnabled(true);
    }

    void hakAksesBidan() {
        Pasien.setEnabled(true);
        Bidan.setEnabled(false);
        Kode_tindakan.setEnabled(true);
        Obat.setEnabled(true);
    }
}
