/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package klinikkebidanan;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author user
 */
public class Form_pemeriksaan extends javax.swing.JFrame {
java.util.Date tglsekarang = new java.util.Date();
    private SimpleDateFormat smpdtfmt = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
    private String tanggal = smpdtfmt.format(tglsekarang);
    
       Statement stm;
       Connection Con;
    /**
     * Creates new form tindakan
     */
    public Form_pemeriksaan() {
        initComponents();
        setLocationRelativeTo(this);
        setJam();
        tgl.setText(tanggal);
        tampil(false);
        aktif(false);
        tabel(false);
        nyala(false);
        open_db();
    }
public final void setJam(){
ActionListener taskPerformer = new ActionListener() {

 @Override
public void actionPerformed(ActionEvent evt) {
String nol_jam = "", nol_menit = "",nol_detik = "";

java.util.Date dateTime = new java.util.Date();
int nilai_jam = dateTime.getHours();
int nilai_menit = dateTime.getMinutes();
int nilai_detik = dateTime.getSeconds();

if(nilai_jam <= 9) nol_jam= "0";
if(nilai_menit <= 9) nol_menit= "0";
if(nilai_detik <= 9) nol_detik= "0";

String jam = nol_jam + Integer.toString(nilai_jam);
String menit = nol_menit + Integer.toString(nilai_menit);
String detik = nol_detik + Integer.toString(nilai_detik);

lblwktu.setText(jam+":"+menit+":"+detik+"");
}
};
new Timer(1000, taskPerformer).start();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtrin6 = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblwktu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtno_rm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnm = new javax.swing.JTextField();
        txthar = new javax.swing.JTextField();
        btcari = new javax.swing.JButton();
        cmbtin = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txthar_ruang = new javax.swing.JTextField();
        cmbruang = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtada = new javax.swing.JTextField();
        cmbnopet = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        txtnamapet = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cmbjenkel = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        tinggi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        berat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tekanan = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtdiagnosa = new javax.swing.JTextField();
        txtno_periksa = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        suhu = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        daftar_obat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btsimpan = new javax.swing.JButton();
        btbatal = new javax.swing.JButton();
        btkeluar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();

        txtrin6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrin6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Tindakan Pemeriksaan");
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Tanggal :");

        tgl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tgl.setForeground(new java.awt.Color(0, 204, 204));
        tgl.setText("Tanggal");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Jam :");

        lblwktu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblwktu.setForeground(new java.awt.Color(0, 204, 204));
        lblwktu.setText("Jam");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tindakan Pemeriksaan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(tgl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblwktu)))
                .addGap(570, 570, 570))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(423, 423, 423)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgl)
                    .addComponent(jLabel2)
                    .addComponent(lblwktu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDesktopPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        txtno_rm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtno_rmActionPerformed(evt);
            }
        });

        jLabel7.setText("No Pasien");

        jLabel8.setText("Nama Pasien");

        jLabel5.setText("Nama Tindakan");

        jLabel6.setText("Harga Tindakan");

        btcari.setBackground(new java.awt.Color(255, 255, 255));
        btcari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btcari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/carii.png"))); // NOI18N
        btcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcariActionPerformed(evt);
            }
        });

        cmbtin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbtin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TINDAKAN", "Suntik KB 1 Bulan", "Suntik KB 3 Bulan", "Imunisasi DPT", "Imunisasi Polio", "Imunisasi BCG", "Periksa Kehamilan", "Pengobatan Anak", "Persalinan" }));
        cmbtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtinActionPerformed(evt);
            }
        });

        jLabel24.setText("Lama Menginap");

        jLabel25.setText("Harga Ruang");

        txthar_ruang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthar_ruangActionPerformed(evt);
            }
        });

        cmbruang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbruang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LAMA MENGINAP", "1 Hari", "2 Hari", "3 Hari", "4 Hari", "5 Hari", "6 Hari", "7 Hari" }));
        cmbruang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbruangActionPerformed(evt);
            }
        });

        jLabel26.setText("Keadaan Bayi");

        jLabel27.setText("Jenis Kelamin Bayi");

        cmbnopet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbnopet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BIDAN", "B-001", "B-002" }));
        cmbnopet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbnopetActionPerformed(evt);
            }
        });

        jLabel13.setText("No. Bidan");

        jLabel14.setText("Nama Bidan");

        jLabel21.setText("Diagnosa");

        cmbjenkel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbjenkel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JENIS KELAMIN", "Laki-laki", "Perempuan" }));
        cmbjenkel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbjenkelActionPerformed(evt);
            }
        });

        jLabel4.setText("Tinggi Badan");

        jLabel10.setText("Berat Badan");

        jLabel11.setText("Tekanan Darah");

        tekanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekananActionPerformed(evt);
            }
        });

        jLabel28.setText("Cm");

        jLabel29.setText("Kg");

        jLabel30.setText("mmHg");

        txtno_periksa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtno_periksa.setText("No Periksa");

        jLabel12.setText("Suhu Badan");

        jLabel31.setText("C");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel21)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtno_rm, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btcari, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbruang, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                                .addComponent(txthar_ruang, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txthar, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cmbtin, 0, 174, Short.MAX_VALUE)
                                                .addComponent(txtnm))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(suhu, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tekanan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                                    .addComponent(berat, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tinggi, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel28)
                                                    .addComponent(jLabel29)
                                                    .addComponent(jLabel30)
                                                    .addComponent(jLabel31))))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbjenkel, 0, 178, Short.MAX_VALUE)
                                    .addComponent(txtnamapet)
                                    .addComponent(cmbnopet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtdiagnosa))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtno_periksa))
                        .addGap(0, 267, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtno_periksa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btcari)
                    .addComponent(jLabel7)
                    .addComponent(txtno_rm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(berat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tekanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(suhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbtin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txthar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(cmbruang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txthar_ruang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(cmbjenkel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cmbnopet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtnamapet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtdiagnosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Rincian Obat");

        jLabel9.setText("Daftar Obat");

        daftar_obat.setColumns(20);
        daftar_obat.setRows(5);
        jScrollPane1.setViewportView(daftar_obat);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setToolTipText("");
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 153, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NAMA OBAT", "JENIS OBAT", "KETERANGAN"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel23)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        btsimpan.setBackground(new java.awt.Color(255, 255, 255));
        btsimpan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save.png"))); // NOI18N
        btsimpan.setText(" Simpan");
        btsimpan.setBorder(null);
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });

        btbatal.setBackground(new java.awt.Color(255, 255, 255));
        btbatal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/error.png"))); // NOI18N
        btbatal.setText(" Batal");
        btbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatalActionPerformed(evt);
            }
        });

        btkeluar.setBackground(new java.awt.Color(255, 255, 255));
        btkeluar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/keluarrr.png"))); // NOI18N
        btkeluar.setText(" Keluar");
        btkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(btsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btbatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));

        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NAMA TINDAKAN", "DIAGNOSA", "DAFTAR OBAT", "TANGGAL", "JAM"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("RIWAYAT PASIEN");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkeluarActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btkeluarActionPerformed

    private void btbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatalActionPerformed
        txtno_periksa.setText("No Periksa");
        txtno_rm.setText("");
        txtnm.setText("");
        cmbtin.setSelectedItem(0);
        txthar.setText("");
        cmbruang.setSelectedItem(0);
        cmbjenkel.setSelectedItem(0);
        cmbnopet.setSelectedItem("BIDAN");
        txthar_ruang.setText("");
        txtada.setText("");
        txtdiagnosa.setText("");
        txtnamapet.setText("");
        tinggi.setText("");
        berat.setText("");
        tekanan.setText("");
        daftar_obat.setText("");
        suhu.setText("");
        jTable1.setModel(new DefaultTableModel(
    new Object [ ][ ] {},
    new String [ ] 
    {"NAMA OBAT","JENIS OBAT"}));
    jTable2.setModel(new DefaultTableModel(
    new Object [ ][ ] {},
    new String [ ] 
    {"NAMA TINDAKAN","DIAGNOSA","DAFTAR OBAT","TANGGAL","JAM"}));
        tabel(false);
        tampil(false);
        aktif(false);
        nyala(false);
    }//GEN-LAST:event_btbatalActionPerformed

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
String no_periksa =txtno_periksa.getText();
String no_rm = txtno_rm.getText();
String nama = txtnm.getText();
String kd_tin = (String) cmbtin.getSelectedItem();
String harga_tindakan = (String) txthar.getText();
String ruang_bersalin = (String) cmbruang.getSelectedItem();
String harga_ruang = txthar_ruang.getText();
String keadaan_bayi = txtada.getText();
String jenkel_bayi = (String) cmbjenkel.getSelectedItem();
String no_bidan = (String) cmbnopet.getSelectedItem();
String nama_bidan = txtnamapet.getText();
String diagnosa = txtdiagnosa.getText();
String Tinggi = tinggi.getText();
String Berat = berat.getText();
String Tekanan = tekanan.getText();
String DaftarObat = daftar_obat.getText();
String tanggal = tgl.getText();
String jam = lblwktu.getText();
String suhu_bdn = suhu.getText();
{
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
Connection koneksi = (Connection) DriverManager.getConnection(
"jdbc:mysql://localhost:3306/rumahbersalin", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="insert into periksa values('"+no_periksa+"','"+no_rm+"','"+nama+"','"+kd_tin+"','"+harga_tindakan+"','"+ruang_bersalin+"','"+harga_ruang+"','"+keadaan_bayi+"','"+jenkel_bayi+"','"+no_bidan+"','"+nama_bidan+"','"+diagnosa+"','"+DaftarObat+"','"+Tinggi+"','"+Berat+"','"+Tekanan+"','"+tanggal+"','"+jam+"','"+suhu_bdn+"')";
int executeUpdate = statement.executeUpdate(sql);
statement.close();
JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
aktif(false);
        txtno_periksa.setText("No Periksa");
        txtno_rm.setText("");
        txtnm.setText("");
        cmbtin.setSelectedItem("TINDAKAN");
        txthar.setText("");
        cmbruang.setSelectedItem(0);
        cmbjenkel.setSelectedItem(0);
        cmbnopet.setSelectedItem("BIDAN");
        txthar_ruang.setText("");
        txtada.setText("");
        txtdiagnosa.setText("");
        txtnamapet.setText("");
        tinggi.setText("");
        berat.setText("");
        tekanan.setText("");
        daftar_obat.setText("");
        suhu.setText("");
         jTable1.setModel(new DefaultTableModel(
    new Object [ ][ ] {},
    new String [ ] 
    {"NAMA OBAT","JENIS OBAT"}));
    jTable2.setModel(new DefaultTableModel(
    new Object [ ][ ] {},
    new String [ ] 
    {"NAMA TINDAKAN","DIAGNOSA","DAFTAR OBAT","TANGGAL","JAM"}));
        koneksi.close();
}
catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
{
JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}
    }
    }//GEN-LAST:event_btsimpanActionPerformed

    private void txtrin6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrin6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrin6ActionPerformed

    private void cmbnopetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbnopetActionPerformed
    data_petugas();
    }//GEN-LAST:event_cmbnopetActionPerformed

    private void cmbruangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbruangActionPerformed
      if(cmbruang.getSelectedItem().equals("1 Hari")){  
      txthar_ruang.setText("125000");  
  } 
       else if(cmbruang.getSelectedItem().equals("2 Hari")){  
      txthar_ruang.setText("250000");  
  } 
       else if(cmbruang.getSelectedItem().equals("3 Hari")){  
      txthar_ruang.setText("375000");  
  }    else if(cmbruang.getSelectedItem().equals("4 Hari")){  
      txthar_ruang.setText("500000");  
  } 
       else if(cmbruang.getSelectedItem().equals("5 Hari")){  
      txthar_ruang.setText("625000");  
  } 
       else if(cmbruang.getSelectedItem().equals("6 Hari")){  
      txthar_ruang.setText("750000");  
  } 
       else if(cmbruang.getSelectedItem().equals("7 Hari")){  
      txthar_ruang.setText("875000");  
  } 
       else{txthar_ruang.setText("0");  
  }
    }//GEN-LAST:event_cmbruangActionPerformed

    private void cmbtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtinActionPerformed
data_tindakan();  
if(cmbtin.getSelectedItem().equals("Persalinan")){  
nyala(true);
aktif(true);
tabel(true);
tampilkan_data();
}else if(cmbtin.getSelectedItem().equals("Suntik KB 1 Bulan")){nyala(false);ruang();
aktif(false);
}else if(cmbtin.getSelectedItem().equals("Suntik KB 3 Bulan")){nyala(false);ruang();
aktif(false);
}else if(cmbtin.getSelectedItem().equals("Imunisasi DPT")){nyala(false);ruang();
aktif(false);
}else if(cmbtin.getSelectedItem().equals("Imunisasi Polio")){nyala(false);ruang();
aktif(false);
}else if(cmbtin.getSelectedItem().equals("Imunisasi BCG")){nyala(false);ruang();
aktif(false);
}else if(cmbtin.getSelectedItem().equals("Periksa Kehamilan")){nyala(true);ruang();
aktif(false);
tabel(true);
tampilkan_data();
}else if(cmbtin.getSelectedItem().equals("Pengobatan Anak")){nyala(true);
ruang();
aktif(false);
tabel(true);
tampilkan_data();
}
    }//GEN-LAST:event_cmbtinActionPerformed

    private void btcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcariActionPerformed
        cari_riwayat();
        String no_pasien = txtno_rm.getText();
        String tanggal = tgl.getText();
        try
        {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = (Connection) DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/rumahbersalin", "root", "");
            Statement statement = (Statement) koneksi.createStatement();
            String sql="SELECT * FROM daftar WHERE no_rm like '"+no_pasien+"' AND tanggal like '"+tanggal+"'";
            ResultSet rs = statement.executeQuery(sql);
            if (rs.next())
            {
                txtnm.setText(rs.getString(5));
                tinggi.setText(rs.getString(10));
                berat.setText(rs.getString(11));
                tekanan.setText(rs.getString(12));
                suhu.setText(rs.getString(13));
                JOptionPane.showMessageDialog(null, "Data ditemukan","Informasi",JOptionPane.INFORMATION_MESSAGE);
                otomatis();
                tampil(true);
                tabel(false);
                aktif(false);
                edit(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan ","Informasi",JOptionPane.INFORMATION_MESSAGE);
            }
            statement.close();
            koneksi.close();
        }
        catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
            //System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_btcariActionPerformed

    private void tekananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tekananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tekananActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       String[] selectedTableRecords = getJtableSelectedRowsData(jTable1);
       StringBuilder sb = new StringBuilder();
       for (String str : selectedTableRecords) {
           sb.append(str).append(System.lineSeparator());
       }
      daftar_obat.setText(sb.toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void txthar_ruangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthar_ruangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthar_ruangActionPerformed

    private void txtno_rmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtno_rmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtno_rmActionPerformed

    private void cmbjenkelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbjenkelActionPerformed
       if(cmbjenkel.getSelectedItem().equals("Laki-laki")){   
  } 
       else{cmbjenkel.getSelectedItem().equals("Perempuan");  
  }
    }//GEN-LAST:event_cmbjenkelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_pemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Form_pemeriksaan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField berat;
    private javax.swing.JButton btbatal;
    private javax.swing.JButton btcari;
    private javax.swing.JButton btkeluar;
    private javax.swing.JButton btsimpan;
    private javax.swing.JComboBox<String> cmbjenkel;
    private javax.swing.JComboBox cmbnopet;
    private javax.swing.JComboBox cmbruang;
    private javax.swing.JComboBox cmbtin;
    private javax.swing.JTextArea daftar_obat;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblwktu;
    private javax.swing.JTextField suhu;
    private javax.swing.JTextField tekanan;
    private javax.swing.JLabel tgl;
    private javax.swing.JTextField tinggi;
    private javax.swing.JTextField txtada;
    private javax.swing.JTextField txtdiagnosa;
    private javax.swing.JTextField txthar;
    private javax.swing.JTextField txthar_ruang;
    private javax.swing.JTextField txtnamapet;
    private javax.swing.JTextField txtnm;
    private javax.swing.JLabel txtno_periksa;
    private javax.swing.JTextField txtno_rm;
    private javax.swing.JTextField txtrin6;
    // End of variables declaration//GEN-END:variables

    


    private void data_tindakan() {
  String kd_tin = (String) cmbtin.getSelectedItem();
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
Connection koneksi = (Connection) DriverManager.getConnection(
"jdbc:mysql://localhost:3306/rumahbersalin", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="SELECT * FROM tindakan where nama_tin like '"+kd_tin+"'";
 ResultSet rs = statement.executeQuery(sql);
if (rs.next())
{
txthar.setText(rs.getString(3));
} 
else {
JOptionPane.showMessageDialog(null, "Data Tidak Ada");
} } catch (Exception e){ }
}

    private void aktif(boolean x) { 
      tinggi.setEditable(x);
      berat.setEditable(x);
      tekanan.setEditable(x);
      suhu.setEditable(x);
      txtnm.setEditable(x);
      txthar.setEditable(x);
      txtnamapet.setEditable(x);
      txthar_ruang.setEditable(x);
      cmbruang.setEnabled(x);
      txtada.setEditable(x);
      cmbjenkel.setEnabled(x);
    }
    

    private void data_petugas() {
String nip = (String) cmbnopet.getSelectedItem();
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
Connection koneksi = (Connection) DriverManager.getConnection(
"jdbc:mysql://localhost:3306/rumahbersalin", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="SELECT * FROM bidan WHERE nip like '"+nip+"'";
 ResultSet rs = statement.executeQuery(sql);
if (rs.next())
{
txtnamapet.setText(rs.getString(2));
} else {
} } catch (Exception e){ }
    }
    
    private void nyala(boolean a) {
      daftar_obat.setEditable(a);
    }
      private void open_db() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/rumahbersalin","root","");
            stm = (Statement) Con.createStatement();

        }catch (ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null,"Koneksi gagal");
            System.out.println(e.getMessage());
        }
    }

    private void tampilkan_data() {
         DefaultTableModel tabelmapel = new DefaultTableModel();
        tabelmapel.addColumn("NAMA OBAT");
        tabelmapel.addColumn("JENIS OBAT");
        tabelmapel.addColumn("KETERANGAN");
        try {
            open_db();
            String sql = "SELECT * FROM obat ORDER BY nama_obat ASC";
            stm = (Statement) Con.createStatement();
            ResultSet rs=stm.executeQuery(sql);
            while (rs.next()) {
                Object[] o =new Object[3];
                o[0] = rs.getString("nama_obat");
                o[1] = rs.getString("jenis");
                o[2] = rs.getString("keterangan");
                tabelmapel.addRow(o);
                
            }
           jTable1.setModel(tabelmapel);
        } catch (Exception e) {
        }
    }

    private void tampil(boolean x) {
      cmbnopet.setEnabled(x);
      cmbtin.setEnabled(x);
    }

    private void tabel(boolean b) {
        jTable1.setEnabled(b);
    }
   

    private String[] getJtableSelectedRowsData(JTable jTable1) {
        int[] selectedRows = jTable1.getSelectedRows();
        String[] resultArray = new String[selectedRows.length];
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int nCol = dtm.getColumnCount();
        
        for (int i = 0; i < selectedRows.length; i++){
            String resultString ="";
            for (int j=0; j < nCol; j++){
                resultString += resultString.equals("") ? dtm.getValueAt(selectedRows[i], j).toString()
                        : "," + dtm.getValueAt(selectedRows[i], j).toString();
            }
            resultArray[i]= resultString;
        }
        return resultArray;
    }

    private void otomatis() {
       try {
            open_db();
            String sql="select right (no_periksa,2)+1 from periksa";
            ResultSet rs=stm.executeQuery(sql);
            if(rs.next()){
                rs.last();
                String no=rs.getString(1);
                while (no.length()<3){
                    no="0"+no;
                    txtno_periksa.setText("PM-"+no);}
                }
            else
            {
                txtno_periksa.setText("PM-001"); 
            }
            } catch (Exception e) 
            {
        }
    }

    private void edit(boolean x) {
      tinggi.setEditable(x);
      berat.setEditable(x);
      tekanan.setEditable(x);
      suhu.setEditable(x);
    }

    private void ruang() {
       txthar_ruang.setText("0");
    }

    private void cari_riwayat() {
DefaultTableModel tabelnyo = new DefaultTableModel();
tabelnyo.addColumn("NAMA TINDAKAN");
tabelnyo.addColumn("DIAGNOSA");
tabelnyo.addColumn("DAFTAR OBAT");
tabelnyo.addColumn("TANGGAL");
tabelnyo.addColumn("JAM");
try{
open_db();
String sql = "Select * from periksa where no_rm like '%" + txtno_rm.getText() + "%'" +
"or nama like '%" + txtno_rm.getText() + "%'";
ResultSet rs = stm.executeQuery(sql);
while (rs.next()) {
tabelnyo.addRow(new Object[]{
rs.getString(4),
rs.getString(12),
rs.getString(13),
rs.getString(17),
rs.getString(18)    
});
}
jTable2.setModel(tabelnyo);

}catch (Exception e){
}
    }

    private void ruang_aktif(boolean b) {
        cmbruang.setEnabled(b);
    }
}
